### ISSUE TITLE
About the strings.xml

### ISSUE THREAD

**Issue by safakesberk** [FallenRiteMonk/ludus#3]
Hi,

I wanted translate your game but I can't found correct strings.xml file. Am I missing something?

Your xml file  :<a href=https://github.com/FallenRiteMonk/ludus/blob/dev/app/src/main/res/values/strings.xml>Link</a>

**Comment by FallenRiteMonk** [comment]
Hy,
I have just started to port the project to plain android, so there isn't to much ready yet. To be honest I actually didn't think someone is going to contribute this fast, but If you want I can try to write together some parts that I may need, depending on the old project and you can start translating those.
I would also appreciate if you would translate the google play page! If you would like to get started with that in the main wile!

Thanks and greetings,
FallenRiteMonk

**Comment by safakesberk** [comment]
Hi again, 

Don't hesitate about all of this. When you have free time, you can prepare strings.xml. After then I can translate.

As to google play page, here is your translation (It's not verbatim translate but it looks more understandable)

"Ludus, herkesin basitçe oynayabileceği bir kombinasyon oyunudur. Bu oyun genellikle kağıt üstünde oynanırdı ama artık tüm bu kağıt israfını durdurabilir ve tüm android cihazlarınızda oynayabilirsiniz.

Hangi kombinasyon ile en iyi sonucu alırsınız? Bu karar sizi düşünmeye teşvik edecek. Doğru kombinasyonları bulabilmek için bütün dikkatinizi de oyuna vermelisiniz.

Şu anda uygulama aşağıdaki özellikleri içerir :
- Kağıtsız oyun oynama
- Oyunu kaydetme ve kaldığı yerden devam edebilme
- Bir sonraki kombinasyonu bulamadığınızda ipucu alabilme
- Arkadaşlarınızla kıyaslayabilmeniz için istatistikler

Bu oyun herhangi bir sınırlama olmaksızın tamamen ücretsizdir."

When I can help you, please contact me. Greetings..

**Comment by FallenRiteMonk** [comment]
Hy,

as allready told, I added the strings from version 1 of the game. It might be that there isn't going to ba use for all of them, but the most of them should be fine! I also added a resources folder in the root of he project, where I'm going to manage all the external resources of the project, and created a subfolder strings where texts for play store and play services lie. Could you please put your translation there and maybe also complete it. I hope it's pretty self explanatory, as I didn't put any explanation into the readme yet!

Thanks and greetings

**Comment by FallenRiteMonk** [comment]
Hy,
I have added a small part to the google play store description to link to the github page, could you please update that to?

Thanks and Greetings,
FallenRiteMonk

**Comment by safakesberk** [comment]
I had translated, I sent PR. Greetings..
